### ISSUE TITLE
Original FW dump for OTA

### ISSUE THREAD

**Issue by LoriLori** [rbaron/fitless#1]
Would you have factory FW dump somewhere? 
App tries to access http://www.youduoyun.com/apps/firmwares/firmware.json but 
{
	"firmwareInfo": [{
		"device_id": "19",
		"version": "1",
		"file": "http://192.168.2.188/id107_plus_dfu_v42.zip",
		"info_ch": "1, ?????????1;\n  2, ?????????2;\n  3, ?????????3.",
		"info_en": "1, test1;\n  2, test2;\n  3, test3."
	}]
}
One could upload new FW via nRF OTA functionality without disassembly

**Comment by ctz** [comment]
https://github.com/ctz/id115-firmware-dump has a dump from mine. However that's a raw flash dump, not OTA.

**Comment by rbaron** [comment]
Hi @LoriLori. Unfortunately I have not. I would also be interested in it. Let me know if @ctz's suggestion works for you.

@ctz thanks for jumping in! I'll take a look at your dump.

**Comment by LoriLori** [comment]
Thanks! @ctz and @rbaron works fine :) App vect. table starts at 0x18000 above it is softdevice, need to find matching softdevice version to match SVCs id. OTA DFU is there, we can start some opensource FW fun. Time to buy watch. I like its size. Rather then Diggro DB-01 which also has nRF.

**Comment by LoriLori** [comment]
Softdevice is S110 v8.0.0 https://devzone.nordicsemi.com/f/nordic-q-a/1171/how-do-i-access-softdevice-version-string#post-id-3693 http://www.nordicsemi.com/eng/nordic/Products/nRF51822/S110-SD-v8/45846 and that is why app starts at 0x18000

**Comment by fanoush** [comment]
> . OTA DFU is there, we can start some opensource FW fun. Time to buy watch.

So did it work for you and you successfully created and flashed OTA to your ID115 or you need to buy watch first?

Few days ago I finally got ID115 bracelet which is not a clone and/or seems to contain real Nordic chipset. I managed to switch it to OTA mode  via writing 0x01 0x01 to 00000af6-0000-1000-8000-00805f9b34fb  and see arrow on screen. The veryfit pro app says it is ID115 firmware version 27. @ctz how can I check your dump may indeed match my device without opening it? Can I check some BLE service/attribute either in normal or DFU OTA mode to double check your dump is usable for me? Is your FW also 27? And how can I in fact make flashable OTA/DFU package from this dump bin file to try? Thanks a lot.

BTW, this is my third visually almost identical ID115 bracelet. It is quite hard to get something with nordic chipset. The first one has Realtek 8762AG inside (and uses DayDay Band andorid app) and second one has some variant of Telink TLSR8266 and uses YOHO sports app. And of course both sellers listed it has nordic chip inside.

**Comment by LoriLori** [comment]
Sorry @fanoush (sounds Czech?) no luck getting Id115 with nordic :( Abandoned it.

**Comment by fanoush** [comment]
I just got one from https://www.gearbest.com/smart-watches/pp_616051.html?wid=1527929

**Comment by tjhasan** [comment]
Any update on this thread? Currently stuck on the same step as @fanoush

**Comment by fanoush** [comment]
oh, it is 3 years, a lot happened since then, now there are fitness trackers and smartwatches with 52832 and 52840 that are much better than this. I still do have this ID115 and  could make OTA but it only has 16kB RAM and 256KB flash so I never did. I spent time with 52832 based ones instead see https://github.com/fanoush/ds-d6
However it is possible to make ota, ID115 is using softdevice S110 8.0 so needs nordic SDK10 to develop for https://infocenter.nordicsemi.com/topic/com.nordic.infocenter.sdk51.v10.0.0/index.html?cp=8_5_14  Most likely it can be also upgraded via  OTA up to to S130/SDK12 which is latest one to support nrf51. I am mostly focusing on Espruino and that one is very tight fit for nrf51 so not sure it would fit ID115 with everything needed.

**Comment by tjhasan** [comment]
I see. For various reasons I can only work with the ID115 right now. Which is why I'm reaching out for help :( . 

Specifically, I'm currently trying to conduct the fw update on the ID115 using some of the examples that exist on the `nRF51 SDK v100`. For examples, I compile the the .hex files found in the directory: `sdk\examples\dfu\ble_dfu_send_hex\test_images_update_nrf51` **or** `sdk\examples\ble_peripheral\ble_app_hrs\pca10028\s110_with_dfu\` and create the .zip image folder. After that I attempt the ota but I always receive the error "Operation Failed" error during the update.

Should I create the firmware a different way? I know that it is possible to make the ota but I think I'm having some trouble actually doing it :(

**Comment by fanoush** [comment]
> Should I create the firmware a different way?

You did not say how you create it but yes. at least for other dfu zips for other IDxxx devices from same company you need to create the zip with proper `--dev-type`  `--dev-revision`. BTW if you switch it to DFU mode and then start VeryFit Pro app and try to connect to it, it will notice it is in dfu mode and it will download and update the device with latest matching firmware (which may still be lower version than you currently have, mine is version 35). The OTA zip can be then found somewhere on the phone storage in Android/data/com.veryfit2hr.second/ folder. If you already have firmware file check the dat file inside. Also there is device_update folder that has some log file with device firmware id. mine is 553 so the dat file inside firmware starts with 29 02 FF FF, 0x229=553

Did you take apart your device? Do you have a plan when DFU succeeds? how do you plan to update it second time? BTW build made for nordic devboard (pca10028) may have some board specific code (leds, buttons,..) that may not work with other device. Also not sure if ID115 has low frequency crystal, nordic devboards typically have it and the code will not work in device without one (=pca10028 will probably have LF clock set to  NRF_CLOCK_LF_SRC_Xtal). Also pca10028 has 32kB of ram so you need linker script with only 16kB RAM section. I'd suggest to test with some bare nrf51 module first.

**Comment by placeHolders23** [comment]
> I managed to switch it to OTA mode via writing 0x01 0x01 to 00000af6-0000-1000-8000-00805f9b34fb and see arrow on screen. 

Hi @fanoush I created a GitHub account just to ask this question, how did you figure out that you need to send 0x01 0x01 to that characteristic to switch the device to OTA mode? Was it in the .apk? Trying to reverse engineer more devices and using this device as a learning step so any help would be appreciated!

**Comment by fanoush** [comment]
Well, it is common way all these IDOO devices that use VeryFit apps work, and yes it is in the veryfit apk somewhere. Also other ways are logging bluetooth traffic on the phone or using some mitm proxy (BtleJuice). Also the firmware itself can be decompiled e.g. with Ghidra. actually I don't remember where I got this one from :-)

btw you can find some other ppl doing this in https://gitter.im/nRF51822-Arduino-Mbed-smart-watch/Lobby or [atc1441's discord server](https://gitter.im/nRF51822-Arduino-Mbed-smart-watch/Lobby?at=5f4e2c2f765d633c54c8fcfd)
